<?php
/**
* This file is released under a custom license by Avenla Oy.
* All rights reserved
* 
* License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/ 
* For questions and support - klarna-support@avenla.com
* 
* @category   Avenla
* @package    Avenla_KlarnaCheckout
* @copyright  Copyright (c) Avenla Oy
* @link       http://www.avenla.fi 
*/

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>
<?php if ($this->getRequest()->getActionName() == "view"): ?>
	
	<img src="<?php echo $imgSrc; ?>" alt="Klarna Checkout" />
	<a href="<?php echo $guiUrl; ?>" target="_blank" style="float:right"><?php echo $this->__('Klarna online GUI'); ?></a>

	<?php if (count($info->getAdditionalInformation("klarna_order_invoice")) > 0): ?>
		
		<?php foreach($info->getAdditionalInformation("klarna_order_invoice") as $inv): ?>
			<p>
				<b><?php echo $this->__('Klarna Invoice number: %s', $inv["invoice"]); ?></b>
				<?php if(isset($pdfUrl)): ?>
					<a href="<?php echo $pdfUrl . $inv['invoice'] . ".pdf" ?>" target="_blank"><?php echo $this->__('Packing slip'); ?></a>
				<?php endif; ?>
			</p>
		<?php endforeach; ?>
	
	<?php endif; ?>  
	  
	<?php if($this->getInfo()->getOrder()->getState() != Mage_Sales_Model_Order::STATE_COMPLETE): ?>
		<p><b>    
			<?php echo $this->__('Klarna reservation number: %s', $info->getAdditionalInformation("klarna_order_reservation"));?>
		  
			<?php if (strlen($info->getAdditionalInformation("klarna_order_reservation_expiration")) > 0): ?>
				<p>
					<?php echo $this->__('Klarna reservation expires: %s',
						Mage::helper('core')->formatDate($info->getAdditionalInformation("klarna_order_reservation_expiration"), 'medium', false)); ?>
				</p>
				
				<?php 
					$temp_time = strtotime($info->getAdditionalInformation("klarna_order_reservation_expiration"));
					$expiration = new Zend_Date($info->getAdditionalInformation("klarna_order_reservation_expiration"));
					$now = new Zend_Date();
				?>
				<?php if(strtotime($info->getAdditionalInformation("klarna_order_reservation_expiration")) < $now->get()): ?>
					<p class="klarnaAlert" style="font-weight:bold; color:red;"><?php echo $this->__('Klarna reservation has expired.'); ?></p>
				<?php endif; ?>
			<?php endif; ?>
		</b></p>
	<?php endif; ?>

	<?php if(isset($message)): ?>
		<p><b><?php echo $message; ?></b></p>
	<?php endif; ?>
	
<?php else: ?>
	<p>Klarna Checkout</p>
<?php endif; ?>