<?php
/**
 * This file is released under a custom license by Avenla Oy.
 * All rights reserved
 * 
 * License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/ 
 * For questions and support - klarna-support@avenla.com
 * 
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 * @copyright  Copyright (c) Avenla Oy
 * @link       http://www.avenla.fi 
 */

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>
<?php if($this->getWidgetType() == "klarna"): ?>
	<?php $params = $this->getWidgetData(); ?>
	<?php if($params['price']): ?>
		<div style="width:<?php echo $params['width']; ?>px; height:<?php echo $params['height']; ?>px" 
		     class="klarna-widget klarna-part-payment"
		     data-eid="<?php echo $params['eid']; ?>"
		     data-locale="<?php echo $params['locale']; ?>"
		     data-price="<?php echo $params['price']; ?>"
		     data-layout="<?php echo $params['layout']; ?>">
		</div>
	<?php endif; ?>	
<?php elseif($this->getWidgetType() == "product" && $this->getWidgetData()): ?>
	<div class="kco-ppayment">
		<p><?php echo $this->getWidgetData(); ?></p>
		<img src="<?php echo Mage::helper('klarnaCheckout')->getLogoSrc(50); ?>" />
	</div>
<?php endif; ?>