<?php 
/**
 * This file is released under a custom license by Avenla Oy.
 * All rights reserved
 * 
 * License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/ 
 * For questions and support - klarna-support@avenla.com
 * 
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 * @copyright  Copyright (c) Avenla Oy
 * @link       http://www.avenla.fi 
 */

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>

<div id="klarnaMsg" style="display:none"><h2></h2></div>

<div id="klarnaWrapper" name="klarnaWrapper">
    <div id="klarnaOverlay"></div>
    <div id="klarnaFrame"></div>
</div>

<script>
    function loadFrame()
    {
		var kcoloadurl = '<?php echo $this->getUrl("klarnaCheckout/KCO/loadKcoFrame/", array("_secure" => true)) ?>';
		
		if($$('div.payments')[0]){
			if($$('div.payments')[0].getWidth() < 600)
				kcoloadurl = kcoloadurl + 'mobile/1';
		}
	   
        new Ajax.Request(kcoloadurl, {
            method:'POST',
            onSuccess: function(k) {
                var response = eval("(" + k.responseText + ")");
                if(response.msg){
                    $('klarnaMsg').update('<h2>'+ response.msg +'</h2>').show();
                    $('klarnaOverlay').show();
                }
                else{
                    $('klarnaMsg').update('').hide();
                    $('klarnaOverlay').hide();
                }

                if(response.klarnaframe)
                    $('klarnaFrame').update(response.klarnaframe);
            }
        });
    }

    document.observe('dom:loaded', function(){
        loadFrame();
    });

    _send = XMLHttpRequest.prototype.send;
    XMLHttpRequest.prototype.send = function() {
        var callback = this.onreadystatechange;
        this.onreadystatechange = function() {
            if (this.readyState == 4) {
                var response = eval("(" + this.response + ")");
				if(response !== undefined){
				    if (response.klarnaframe === undefined && response.msg === undefined)
						loadFrame();
				}
            }
            callback.apply(this, arguments);
        }
        _send.apply(this, arguments);
    }
</script>